name = "c-lion-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

routes = [{ pattern = "api.kcodes.me", custom_domain = true }]

rules = [
  { type = "Text", globs = ["**/*.txt"], fallthrough = true }
]
